update status check workflow

diff --git a/.github/workflows/status_checks.yaml b/.github/workflows/status_checks.yaml
--- a/.github/workflows/status_checks.yaml
+++ b/.github/workflows/status_checks.yaml
@@ -4,12 +4,17 @@ jobs:
     job_1: 
         runs-on: ubuntu-latest
         steps:
-            - run: echo "Job 1 is started"
-            - run: sleep 20
-            - if: failure()
-              run: echo "Run on failed"
+            - name: Step 1
+              run: sleep 20
+            - name: Step 2
+              run: exit 1
+            - name: Run on step 2 failure
+              if: failure()
+              run: echo 'Step 2 has failed'
+            - if: success()
+              run: echo "Run on success"
             - if: always()
-              run: echo "Job 1:Run on always"
+              run: echo "Run on always"
             - if: cancelled()
               run: echo "Run on cancelled"
 
